#!gmake 

#-----------------------------------------
#Basic Stuff -----------------------------
CC          = g++ 
cc          = gcc

#-----------------------------------------
#Optimization ----------------------------
OPTMAC = -fast

TARGETS = as4

OBJECTS = classes.o as4.o

SOURCES = as4.cpp classes.cpp

#-----------------------------------------
# Mac specific stuff
FRAMEWORK = -framework GLUT
FRAMEWORK += -framework OpenGL
MACLIBS = -lGL -lGLU -lm -lstdc++ -lfreeimage
MACINCS = -L"/System/Library/Frameworks/OpenGL.framework/Libraries" -L./lib/fiosx -I./lib/fiosx -I./include

#-----------------------------------------
CCOPTSMAC = $(OPTMAC) $(MACINCS) -DOSX
LDOPTSMAC = $(OPTMAC) $(MACINCS) $(MACLIBS) -DOSX

#-----------------------------------------
#-----------------------------------------

default: $(TARGETS)

clean:
	/bin/rm -f *.o $(TARGETS)

#-----------------------------------------
#-----------------------------------------

as4: as4.o
	$(CC) $(OBJECTS) $(FRAMEWORK) $(LDOPTSMAC) -o $(TARGETS)

classes.o: classes.cpp
	$(CC) $(SOURCES) -c $(CCOPTSMAC)

as4.o: as4.cpp
	$(CC) $(SOURCES) -c $(CCOPTSMAC)


