#!gmake 

#-----------------------------------------
#Basic Stuff -----------------------------
CC          = g++ 
cc          = gcc

#-----------------------------------------
#Optimization ----------------------------
OPTMAC = -fast

TARGETS = as03

OBJECTS = as03.o

#-----------------------------------------
# Mac specific stuff
FRAMEWORK = -framework GLUT
FRAMEWORK += -framework OpenGL
MACLIBS = -lGL -lGLU -lm -lstdc++ 
MACINCS = -L"/System/Library/Frameworks/OpenGL.framework/Libraries"

#-----------------------------------------
CCOPTSMAC = $(OPTMAC) $(MACINCS) -DOSX
LDOPTSMAC = $(OPTMAC) $(MACINCS) $(MACLIBS) -DOSX

#-----------------------------------------
#-----------------------------------------

default: $(TARGETS)

clean:
	/bin/rm -f *.o $(TARGETS)

#-----------------------------------------
#-----------------------------------------

as03: as03.o
	$(CC) as03.o $(FRAMEWORK) $(LDOPTSMAC) -o as03

as03.o: as03.cpp
	$(CC) as03.cpp -c $(CCOPTSMAC)

