#-Photon Cannon Makefile
CC=g++
cc=gcc

#-LIBRARIES AND INCLUDES
LIBS = -lm -lstdc++ -lfreeimage
INCS = -I include -L./lib/fiosx -I./lib/fiosx 

#OPTIMIZATIONS
OPT = -fast -g -Wall
CCOPTS = $(OPT) $(INCS) -c
LDOPTS = $(OPT) $(INCS) $(LIBS)

#USEFUL INFORMATION
SOURCES=pc.cpp classes.cpp imagewriter.cpp scene.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=pc

#RULES
all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(OBJECTS) $(LDOPTS) -o $@

.cpp.o:
	$(CC) $(CCOPTS) $< -o $@
